version: '2'

networks:
  basic-tier:
    driver: bridge

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: db
    networks:
      - basic-tier
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - basic-tier
  app:
    container_name: ip-geolocation-api
    image: ip-geolocation-api:latest
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_DB_HOST: redis
      REDIS_DB_PORT: 6379
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: secret
      CLIENT_GEOLOCATION_IO: https://api.ipgeolocation.io
      CLIENT_GEOLOCATION_IO_APIKEY: 44c11c25937a47f8bee071e16a3d67fd
      CLIENT_IPAPI: http://api.ipapi.com
      CLIENT_IPAPI_ACCESS_KEY: 7dd289edaf87a821cd8fe2f5774f6655
      CLIENT_API_LAYER: https://api.apilayer.com
      CLIENT_API_LAYER_APIKEY: D6V2ZyOfnx2Fkc1nL7z79PpC3N1ShBOl
      BUENOS_AIRES_LATITUDE: -34.60396
      BUENOS_AIRES_LONGITUDE: -58.44494
      TZ: "GMT-3"

    ports:
      - 8080:8080
    networks:
      - basic-tier